### PR TITLE
fix(wibox: widget: piechart): use math.fmod instead of deprecated math.mod

### PR DESCRIPTION
**Pull request by actionless**
this was breaking the test on my setup

### CODE REVIEW

**Comment by actionless** [comment]
All links in generated `06-appearance.md` are now pointing to `doc/classes/key.html` now.
I am not sure if that because i broke something.

**Comment by Elv13** [comment]
No, it is work in progress

**Comment by Elv13** [comment]
I pushed a upstream_shape_api_p4_unmerged branch with more commits from today. I will merge your remaining changes tomorrow. Thanks

**Comment by actionless** [comment]
i finally enabled shape config for notifications in the latest commit

**Pull request closed without merging**
